### ISSUE TITLE
Cause other mod recipe misbehavior

### ISSUE THREAD

**Issue by FelixAgairu** [Kenny-Hui/RecipeCooldown#1]
Minecraft Fabric Server 1.21.1
Fabric Loader 0.16.5
RecipeCooldown 1.0.0

Misbehavior mod:
[Ore Growth](https://modrinth.com/mod/ore-growth/version/1.1.1b-fabric-mc1.21)

Cause Ore Growth **Crystal** on `minecraft:diamond_ore` `minecraft:deepslate_diamond_ore` drops 1 stack of loot but 1 of item.

**Comment by AmberIsFrozen** [comment]
I've tested with and without RecipeCooldown and it does not seems to make a difference by mining the crystals.
Could you further describe the issue? Thanks

**Comment by FelixAgairu** [comment]
Well this become mess, cause i install about 160 mods on server.
Might with some of mods make this issue not only RecipeCooldown and Ore Growth. But it does drop 64 diamond from ore, only diamond ore, remove RecipeCooldown it drops as normal.

Plus seems I got some another issue that items drop on ground and pick up may gain item count. eg: drop 3 bucket and sometime pick 4 of them.

might `get it together drops`, `staaaaaaaaaaaack`?

**Comment by AmberIsFrozen** [comment]
I've briefly skimmed through Ore Crystal's code and it doesn't seems like there should be any compatibility issues, so I suspect it lies somewhere within that 160 mods (Which is a pain, but if you can send the entire mod list/modpack over, I can hopefully deduce which mod is causing it if I can reproduce it that is)

**Comment by FelixAgairu** [comment]
[Client Spark](https://spark.lucko.me/2cisBYhssh)
[Server Spark](https://spark.lucko.me/PAw2BXrmxc)

Thanks, will also do this later.
So any idea for track what cause issue?

**Comment by AmberIsFrozen** [comment]
No idea yet.
This mod should only affect crafting recipe request coming from the client, so I am a bit surprised it would break interaction this badly, but also this is Minecraft modding so anything is possible :P

**Comment by FelixAgairu** [comment]
Now with some mod clean up, both **Ore Growth** and **RecipeCooldown** works.
_Since I don't have any version control, can't find what mod cause this issue._
![GIF](https://github.com/user-attachments/assets/9b11a687-78f6-4007-9e05-39d8e9682136)


Thanks.
